### ISSUE TITLE
Pearsontown inherits other schools zones

### ISSUE THREAD

**Issue by copelco** [codefordurham/school-navigator#102]
This was discovered researching #86:

Pearsontown has no [assigned attendance zone](http://www.dpsnc.net/files/_AaI16_/adf9dc39f01a638f3745a49013852ec4/Calendar_Magnet_Year-Round_School_Lottery_FAQS_English_2015-16_Assignments.pdf). It's a union of Bethesda, Creekside, Fayetteville Street, Forest View, Hope Valley, Lakewood, Parkwood, W.G. Pearson, E.K. Powe, Y.E. Smith, Southwest and C.C. Spaulding attendance zones.

**Comment by jtf621** [comment]
Pearsontown is a Calendar Magnet Elementary along with Easley and Holt.  See http://www.dpsnc.net/files/_AaI16_/adf9dc39f01a638f3745a49013852ec4/Calendar_Magnet_Year-Round_School_Lottery_FAQS_English_2015-16_Assignments.pdf

and serves people based on there location as described in gisweb2.ci.durham.nc.us/arcgis/rest/services/DurhamMaps/DPS_ElementaryStudentAssignment/MapServer/3/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=html
