### ISSUE TITLE
Classify Charter School level consistently

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#114]
The Charter schools have a widely varying range of grades offered that do not match the traditional Elementary - Middle - High levels that the UI has embedded as an assumption.  Also it will be confusing for a user if a school offering Kindergarten is classified as a middle school.

A few examples are 
- Maureen Joy Charter K-8 (middle)
- Voyager Academy K-12 (secondary)
- Reaching All Minds Academy K-3 (elementary)

#89 also has this issue for  Durham School of the Arts 6-12  "secondary"

**Comment by sarahsba** [comment]
would it make sense to eliminate the elementary/middle/secondary
classifications all together and just show the grades offered?

**Comment by jtf621** [comment]
secondary schools now show up and charters are in a separate tab.  Is this still needed?

**Comment by jtf621** [comment]
see #120

**Comment by lemanal** [comment]
I think that this is fixed with #73. The remaining issue is clearly captured by #120 as @jtf621 noted and can be pushed off for a later phase.
