### ISSUE TITLE
Page doesn't load when with location in URL

### ISSUE THREAD

**Issue by copelco** [codefordurham/school-navigator#128]
For example, if I want to send this link to someone:

https://schools.codefordurham.com/#/location/35.9950478/-78.90066259999998/

The page/map doesn't load properly.

**Comment by victor-rocha** [comment]
It appears that #3031585 broke the frontend as i can't get the the map to load correctly when I check it out, the commit before that #17a6643 works fine.

**Comment by NoOutlet** [comment]
Commit 6170b4acb390cccd168761ed0da86df66c68a2e4 is the culprit.

**Comment by NoOutlet** [comment]
Or is it eb6115cfa7806bf3dc4182f0d313ac44eceb4ad7 ?
