### ISSUE TITLE
5100 torrey pine lane has no assigned elementry school

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#129]

**Comment by copelco** [comment]
Did some research:

Using the [official too](http://gisweb.durhamnc.gov/durhammaps/DPS/viewer/index.html), and searching for ``5100 Torrey Pine Ln``, it also fails. However, if you then use the Select Tool Button, you can select the parcel where the address is labeled, confirm your selection, and it shows that the elementary school should be **Parkwood**.

At first we thought the geocoded point may fall right between two zones. Right across Fayetteville St, the district for **Southwest** starts. If you drag the house icon across the street in our app, you'll see **Southwest** show up. But this doesn't work if you drag the house further into what should be the **Parkwood** district.

There appears to be an issue with the **Parkwood** district and seeing if it contains a point within it. Not sure what it is yet.

**Comment by jtf621** [comment]
Tonight we Chris, Kevin, and I looked at this.  The official site uses property tax maps and the address is located in Pine Ridge Apartments, which has an official address of 6401 Monterrey Creek Dr.

Thanks Chris for the insight on the property tax map issues with apartments.  This will affect other areas in Durham as well.

The elementary is Parkwood with a year round option of Pearsontown.

We need to review the geocoding of the address and the zone shapes for these two school zones to see why we miss.

**Comment by jtf621** [comment]
I compared the shape in https://schools.codefordurham.com/admin/schools/school/194/ and it matches with the official site in the Torrey Pine Lane area.  When I zoom in to https://schools.codefordurham.com/#/location/35.9171635/-78.93060539999999/ and compare it to the admin site, the address should be in the Parkwood district zone.

@copelco is this a query issue?

**Comment by jtf621** [comment]
Found it.  Parkwood was set as not active in the database.  Set it to active (in the admin) and it is fixed.

**Comment by victor-rocha** [comment]
I know Alex set a school as not active a couple of weeks ago but I don't
remember the reason. I wonder if it was this one.

On Tue, Jun 30, 2015 at 10:54 PM, jtf621 <notifications@github.com> wrote:

> Found it. Parkwood was set as not active in the database. Set it to active
> (in the admin) and it is fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/codefordurham/school-navigator/issues/129#issuecomment-117416589>
> .
>



-- 
Thanks,
Victor

**Comment by jtf621** [comment]
Looking at the admin history it was @sarahsba  when she was adding the mission statement and hours to the long list of schools.  I looked online and Parkwood is active.  Changing active was ikely was a fat finger.

**Comment by victor-rocha** [comment]
thanks for checking on that
