### ISSUE TITLE
Update the Assigned tab name and add all schools where the address location indicates a lottery or assignment preference.

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#135]
Spilt from #94.

The interface now shows schools that are designated or are in a walk zone on the Assigned tab based on the address.

- [x] pick a new name for Assigned that better indicates the schools in the list
- [x] add year round options to the list (see #132, #102)
- [x] add priority zones (see #99) others?
- [ ] research Lottery preference, these are the schools with choice or priority given based on the address. There are several different rules for the process

In principal this tab's list should match the results from the (official tool)[http://www.dpsnc.net/pages/Durham_Public_Schools/Our_Schools/Find_Your_School/Find_Your_School_Assignment]

**Comment by adamajm** [comment]
Differentiate formatting for Magnet schools that appear in "assigned" column

**Comment by jtf621** [comment]
incorporated or done
