### ISSUE TITLE
Add Visual User Feedback tool

### ISSUE THREAD

**Issue by adamajm** [codefordurham/school-navigator#137]
like https://usersnap.com/ or

**Comment by lemanal** [comment]
@adamajm Are any of these free?

**Comment by adamajm** [comment]
this one isn't but looks important

http://theuserisdrunk.com/

**Comment by adamajm** [comment]
http://alistapart.com/article/quick-and-dirty-remote-user-testing

**Comment by adamajm** [comment]
From Code for America folks: 

usertesting.com is the one where we have free credits (if useful down the line)
and ethnio and olark are also tools CfA has found useful

**Comment by adamajm** [comment]
Looks like we are good to go with Usersnap! Thanks Alex for making that happen. Now to add to site...

**Comment by lemanal** [comment]
@adamajm Can you QA this?
