### ISSUE TITLE
QA Against DPS Tool

### ISSUE THREAD

**Issue by adamajm** [codefordurham/school-navigator#138]
Prior to any press release or launch, do a final check the listings/school zones @ http://gisweb.durhamnc.gov/durhammaps/DPS/viewer/index.html

Spot check addresses that are on the edge of zones.

**Comment by jtf621** [comment]
Tonight Kevin and I started a list of results from the official list in google docs.  Will attach soon

**Comment by jtf621** [comment]
We should also add a disclaimer like on the official site http://www.dpsnc.net/pages/Durham_Public_Schools/Our_Schools/Find_Your_School/Find_Your_School_Assignment .

    Disclaimers

     This system is subject to current public information rules and regulations. Information presented on this web site is considered public information and may be distributed or copied. The City of Durham, the     County of Durham and Durham Public Schools and its data providers give no warranty, expressed or implied, as to the accuracy, precision, timeliness, completeness, or any other aspect of the data presented. The publisher and data providers assume no liability for damage arrising from the use of this web site or the data provided herein.

 

    If your property is on the line between two school assignment zones please contact the Student     Assignment Office for verification.

**Comment by copelco** [comment]
https://schools.codefordurham.com/api/schools/?latitude=36.018558&longitude=-78.89611400000001

**Comment by jtf621** [comment]
I emulated the DPS tools API calls that the flash app makes in tools/get_dps_py and emulated the front end calls for School Navigator in tools/get_cfd.py (note you need a google api key to call the geocoder).

Next I downloaded from https://opendurham.nc.gov/explore/dataset/parcels1/?tab=table a local copy of the parcels data set.  from this set I randomly pulled out a sample of 1000 site addresses and saved one per line to tools/sample.txt.

with this run 
   python3 get_dps.py < sample.txt > dps.csv
   python3 get_cfd.py < sample.txt > cfd.csv

and analyze with
   python3 compare.py 

and review the results for the differences between the two tools.

**Comment by jtf621** [comment]
The review-dps-cfd.txt report and data files dps.csv and cfd.csv are uploaded to https://drive.google.com/drive/folders/0BzzdkaFnyRitcGhBQ0tmdi0yenc

**Comment by sarahsba** [comment]
This is awesome! Do we know our percent accuracy?

**Comment by jtf621** [comment]
About 98% for high, middle, middle yr, and elementary.  My review suggested that these are largely due to the geocoder edge cases.

About 90% for elementary yr and elementary walk zone. The improvement in #170 will make these numbers be more accurate.

0% for the holt easley traditional option.

**Comment by jtf621** [comment]
@sarahsba  @lemanal  @copelco I reviewed again today after the fixes to #163, #164, and #170.

If we prioritize the fixes to #147 and #152 and confirm we are correct vs the DPS tool for #174 then we should be ~99.9% correct for the sample of 1000 addresses I used.

The review-dps-cfd.txt report and data files dps.csv and cfd.csv are uploaded to https://drive.google.com/drive/folders/0BzzdkaFnyRitcGhBQ0tmdi0yenc

During the review I closed #177 and #168 & opened #173, #174, #175, and #176.

**Comment by jtf621** [comment]
@sarahsba @lemanal @copelco I reviewed again today after the fixes to #152 and #147 went ont production.

The only data differences I find now are #174 and geocode errors for

5357 N ROXBORO ST
5368 N ROXBORO ST
5350 N ROXBORO ST
110 N CORCORAN ST

The review-dps-cfd.txt report and data files dps.csv and cfd.csv are uploaded to https://drive.google.com/drive/folders/0BzzdkaFnyRitcGhBQ0tmdi0yenc

**Comment by lemanal** [comment]
Closing. Merged in PR #171
