### ISSUE TITLE
Distribute parent survey of v1

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#139]
Here's a draft of the survey to share with parents to get feedback on the mapping tool and on the additional information for v2.  Let me know if you have any edits: https://docs.google.com/document/d/1K-U0HmvpewlYQ0Rhha3NhPGBi1D6hGM_pRCVGRJt9UY/edit?usp=sharing

**Comment by lemanal** [comment]
Survey went out. Closed.
