### ISSUE TITLE
2745 Joyner Rd does not have an assigned high school

### ISSUE THREAD

**Issue by NoOutlet** [codefordurham/school-navigator#142]
DPSNC lists Southern as the assigned high school, but doesn't show it on the map. Probably means Southern School of Energy and Sustainability.

Southern High seems to have turned into Southern School of Energy and Sustainability in 2011 when it became a magnet school.

**Comment by NoOutlet** [comment]
Southern appears to have an attendance zone in which students will be assigned automatically to the Southern School of Energy and Sustainability high school.
http://southern.dpsnc.net/pages/Southern_High/About_Us/Magnet_lottery_information

**Comment by jtf621** [comment]
Southern district is found at http://gisweb2.ci.durham.nc.us/arcgis/rest/services/DurhamMaps/DPS_Districts/MapServer/2/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=html
and
http://gisweb2.ci.durham.nc.us/arcgis/rest/services/DurhamMaps/DPS_HighSchoolStudentAssignment/MapServer/2/query?where=1%3D1&text=&objectIds=&time=&geometry=&geometryType=esriGeometryEnvelope&inSR=&spatialRel=esriSpatialRelIntersects&relationParam=&outFields=&returnGeometry=true&maxAllowableOffset=&geometryPrecision=&outSR=&returnIdsOnly=false&returnCountOnly=false&orderByFields=&groupByFieldsForStatistics=&outStatistics=&returnZ=false&returnM=false&gdbVersion=&returnDistinctValues=false&f=html

**Comment by jtf621** [comment]
fixed in #145
