### ISSUE TITLE
update loadschools.py to normalize school names

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#145]
Running current version adds duplicate names
- Club Blvd, Club Boulevard
- Lakewood, Lakewood Elementary School
- Southern, Southern School of Energy and Sustainability
- Y.E. Smith, Y.E. Smith Elementary Museum School

**Comment by jtf621** [comment]
Alternatively we can run the load schools command once and then manually clean up the database one more time before we ship Phase 1.

**Comment by jwaldrep** [comment]
Here is code for normalizing the duplicate school names, inserted at beginning of get_school():
    def get_school(self, name, schools):
        duplicates = {'Club Blvd': 'Club Boulevard',
                      'Lakewood': 'Lakewood Elementary School',
                      'Southern': 'Southern School of Energy and Sustainability',
                      'W.G. Pearson School - Student Services Center': 'W.G. Pearson Magnet Middle School',
                      'Y.E. Smith': 'Y.E. Smith Elementary Museum School'}
        if name in duplicates:
            name = duplicates[name]

I also had to comment out the line with "schools[name] = s" in load_sandy_ridge_priority_zone() in the latest commit in order to test the loadschools command.

**Comment by jtf621** [comment]
thanks @jwaldrep.  I noted that 'W.G. Pearson School - Student Services Center' and 'W.G. Pearson Magnet Middle School' are two different schools.

**Comment by jtf621** [comment]
Performance Learning Center
