### ISSUE TITLE
Add Holt Easley Traditional Calendar option zones

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#147]

**Comment by copelco** [comment]
@jtf621 do you have code started for this or can someone else start fresh?

**Comment by jtf621** [comment]
Someone can start fresh if I am not done before Tuesday

**Comment by jtf621** [comment]
I did not get started yet.  Does someone want to take it on?

**Comment by jtf621** [comment]
starting on it now.

**Comment by jtf621** [comment]
Need multipolygon support to fix

**Comment by jtf621** [comment]
see http://gisweb2.ci.durham.nc.us/arcgis/rest/services/DurhamMaps/DPS_Schools/MapServer/7 for the zones

**Comment by jtf621** [comment]
test cases 

2027 HILLOCK PL                     Eno Valley  
3150 ROSE OF SHARON RD                     Hillandale      
7 GALAXY CT                  Merrick-Moore  
4400 BEN FRANKLIN BLVD                          Glenn

**Comment by jtf621** [comment]
@copelco The data from the API appears correct now.  We need to address drawing the correct polygon on the map.  Do you want to close and open a new ticket for the front end work?

**Comment by copelco** [comment]
Sounds good, the frontend code was fixed in #191
