### ISSUE TITLE
Add List of Schools Page

### ISSUE THREAD

**Issue by adamajm** [codefordurham/school-navigator#149]
Similar to http://www.dpsnc.net/pages/Durham_Public_Schools/Our_Schools

pulling off out database

**Comment by dsummersl** [comment]
I've created a page that based on the DPS page. Here are screenshots: http://imgur.com/a/zRG12

Any feedback for styling?

**Comment by dsummersl** [comment]
PR is here: https://github.com/codefordurham/school-navigator/pull/272

**Comment by lemanal** [comment]
This works great. Thanks @dsummersl ! Closing this out.
