### ISSUE TITLE
5609 kiltshire rd

### ISSUE THREAD

**Issue by lemanal** [codefordurham/school-navigator#152]
Elementary Eno Valley isn't shown in school navigator but shows up in DPS tool. Looks like the district in the DB does not extend west enough.

http://gisweb.durhamnc.gov/durhammaps/DPS/viewer/index.html
https://schools.codefordurham.com/admin/schools/school/201/

**Comment by lemanal** [comment]
District using DPS tool. is split. Is that what the district really looks like? If so, then we need a multi-polygon field in our tool

**Comment by copelco** [comment]
This is fixed in my multipolygon branch
