### ISSUE TITLE
Add charters that opened fall 2015

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#158]
KIPP Durham and possibly more charters are opening in Durham this fall.  We need to find this list and add them to the database.

**Comment by jwaldrep** [comment]
Two charter schools are opening in Durham for Fall 2015, according to: http://www.ncpublicschools.org/docs/charterschools/schools/contactnewcs.pdf

Excelsior Classical Academy http://www.excelsiorca.org/ Cynthia Gadol School Director 919-907-0410 info@excelsior.teamcfa.org 1213 Carolina Ave. Durham, NC 27705

KIPP Durham College Preparatory http://kippenc.org/school-details/kippdurham-college-prep-public-school/ Anders Campbell Principal 252-673-0670 acampbell@kippenc.org PO Box 1521 Durham, NC 27702 Physical Address: 1107 Holloway Street Durham, NC 27701

I am gathering further information on these schools and will post a link to the google doc

**Comment by sarahsba** [comment]
Note updated website for Excelsior: http://excelsior.teamcfa.school/

**Comment by jwaldrep** [comment]
I added the two schools to the database, using the addresses, mission statements, etc. from their websites.

A couple notes:
Updated web address for Kipp is:  http://kippenc.org/school-details/kipp-durham-college-prep-public-school/

Both schools plan to expand their grade levels moving forward, presumably starting next school year.
