### ISSUE TITLE
3612 MORIAH RD confuses geocoder

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#163]
Searching with google maps returns 3 possibilities (the last one is correct)

 -   3612 Mt Moriah Rd, Durham, North Carolina 27707
 -   3612 Moriah Hill Rd, Durham, North Carolina 27707-9567
 -   3612 Moriah Rd, Rougemont, North Carolina 27572-9441

if we update frontend/directives/SearchDirectives.js 

var lookup_address = (scope.address.indexOf("durham") == -1) ? scope.address + " Durham NC": scope.address;
 var lookup_address = (scope.address.indexOf("durham") == -1) ? scope.address + " Durham County NC": scope.address;

this will disambiguate.

**Comment by jtf621** [comment]
@lemanal is this on production yet?  I am testing again.

**Comment by lemanal** [comment]
@jtf621 I did not deploy last week. I don't think it's up on production right now.
