### ISSUE TITLE
110 N CORCORAN ST gecodes to the wrong location

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#165]
Google maps places it south of Main on S CORCORAN  not just north of Main on N CORCORAN which places it in a different elementary school zone (CC Spaulding vs Glenn)

**Comment by lemanal** [comment]
Is there a 110 N Corcoran? 111 Corcoran is N of Main and is the hotel 21c. Are you worried about this as a general problem with the geocoder or a specific problem with this address?

**Comment by lemanal** [comment]
Found this from the assessor's office: http://property.spatialest.com/nc/durham/property/102765/card/1 negating my previous comment. But, isn't that a hole in the ground right now?

**Comment by jtf621** [comment]
The parcel maps have properties that have been sold but construction is not complete. These should be correct for a family that may be evaluating buying a new house. 

Also there are commercial properties in the database. I did not try to filter these out of my sample.

**Comment by jtf621** [comment]
The issue was that the geocoder placed the dot below main and the assessor was north of main. 

The dividing line goes down main.

**Comment by jtf621** [comment]
can't fix the root issue, do #224 instead
