### ISSUE TITLE
the Morehead priority zone sould be on the first tab

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#169]
1017 KENT ST is in the Morehead priority zone.

**Comment by lemanal** [comment]
It's not on the first tab because you would still need to apply to it. The idea is to sort the magnets with matched zones going first. Do you disagree, @jtf621 ?

**Comment by jtf621** [comment]
I think you need to apply to a magnet if you are in a walk zone and they are on the first tab (I think). 

It may be clearer if all of the location based preference are on the first tab. Then tr first tab will provide all of the information that the official site has. 

I could be persuaded to leave it but when I was checking the sample I missed it  on the second tab until I went in the admin.

**Comment by jtf621** [comment]
reviewed with Inessa.
