### ISSUE TITLE
Recommended changes from PTA Council to "Navigating DPS" page

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#178]
NAVIGATOR "NAVIGATING DPS" PAGE

Neighborhood schools - 
I believe Easley is an exception to the first sentence . . . it's a year-round magnet, but also has an automatic attendance zone, which is larger than a walk zone.  If you live in that zone, Easley functions like a traditional school, but it's not "traditional" in the sense that it's year-round. 
In the View Details page, there's a typo in the Calendar section, it says "neighborhoo" instead of neighborhood.

Magnet schools - 

In the View details page, the "What is a walk zone?" section appears twice.

Charter schools - 
There's an extra period at the end of the first sentence.

**Comment by jtf621** [comment]
fixed in #188
