### ISSUE TITLE
Usersnap - yes

### ISSUE THREAD

**Issue by adamajm** [codefordurham/school-navigator#180]
**Sender**: None
**Comment**: yes
[Open #18 in Usersnap Dashboard](https://usersnap.com/a/#/code-for-durham/p/school-navigator-38602a3a/18)

![Usersnap - yes](https://usersnappublic.s3.amazonaws.com/2015-10-05/23-26/5dc51060-54da-4198-a106-de430e0f7790.png)

**Browser**: Safari 8 (iOS)
**Referer**: [https://schools.codefordurham.com/#/](https://schools.codefordurham.com/#/)
**IP**: 24.248.26.122
**Screen size**: 375 x 667 **Browser size**: 375 x 627

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jtf621** [comment]
no useful feedback in usersnap
