### ISSUE TITLE
Update text for walk zone to magnet walk zone

### ISSUE THREAD

**Issue by adamajm** [codefordurham/school-navigator#189]
**Sender**: shapiromatron@gmail.com
**Comment**: Looks great guys, very clean app. I googled my address and club blvd elementary appears, but it's in the "neighborhood", and not in the "magnets". Since it's a magnet school, should it appear in both?

http://clubblvd.dpsnc.net/pages/Club_Boulevard_Elementary

[Open #19 in Usersnap Dashboard](https://usersnap.com/a/#/code-for-durham/p/school-navigator-38602a3a/19)

![Usersnap - isn't club blvd elementary a magnet?](https://usersnappublic.s3.amazonaws.com/2015-10-08/21-06/52f47160-f4c5-4966-9524-ac20a2d39b97.png)

**Browser**: Chrome 45 (Mac OS X Mavericks)
**Referer**: [https://schools.codefordurham.com/#/location/36.021347/-78.89207099999999/](https://schools.codefordurham.com/#/location/36.021347/-78.89207099999999/)
**IP**: 157.98.99.110
**Screen size**: 2560 x 1440 **Browser size**: 2163 x 1112

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by lemanal** [comment]
@jtf621 and @copelco I think we've had this conversation before. Are Walk Zones automatic? Can you opt out?

**Comment by jtf621** [comment]
Assignment is automatic.  You would have to apply to another school.  Presumably, you can apply to the neighborhood school.
see: http://dpsncapplication.com/site327.php

Q: What is a walk zone?
A: A walk zone is an assignment preference that allows automatic assignment to students who live within one (designated safe walking) half mile of the schools that have this preference. Burton Magnet, Club Blvd Magnet and R.N.Harris Magnet Elementary are the only schools that have this assignment preference. A walk zone is not part of the lottery. It acts as an attendance zone, providing automatic assignment throughout the school year.

**Comment by lemanal** [comment]
This is related to #222

**Comment by lemanal** [comment]
This is fixed now that #222 is closed.
