### ISSUE TITLE
Tooltips to explain difference between "Neighborhood", "Magnets" and "Charters"

### ISSUE THREAD

**Issue by emullaney** [codefordurham/school-navigator#198]

**Comment by jtf621** [comment]
@emullaney can you look at #201 and see if you can address it?

**Comment by adamajm** [comment]
Is this already addressed with current release when you hover over "Neighborhood" "Magnet" and "Charter"? or were you thinking something different?

**Comment by lemanal** [comment]
Closing this. I think that this is currently in progress with updates tracked in #201.
