### ISSUE TITLE
Safari issues

### ISSUE THREAD

**Issue by emullaney** [codefordurham/school-navigator#200]
We noticed issues on Safari browser on OSX
- ~~tooltip font size too large, makes "Magnet" tooltip disappear~~
- scrollbar not showing up on the list of schools

**Comment by jtf621** [comment]
- tooltip font size too large, makes "Magnet" tooltip disappear 

is reported in #201, lets track it there

**Comment by jtf621** [comment]
scrollbar shows up when you are scrolling only.

**Comment by lemanal** [comment]
http://stackoverflow.com/questions/6818466/mac-os-x-lion-scrollbars-and-website-usability

**Comment by jtf621** [comment]
The scrolling works and is standard behavior on OSx
