### ISSUE TITLE
Neighborhood/Magnets/Charters tab hover-overs get cut off if message is too long

### ISSUE THREAD

**Issue by ncnwoko** [codefordurham/school-navigator#201]
Tool tip pop-up appears above the tab; risk that msg gets cut off. Consider making it so that pop-up displays below or to the side of the tab. See image
![cfd-hoverover-cutoff](https://cloud.githubusercontent.com/assets/5464067/10403617/1579f954-6e9b-11e5-95d6-8f525ba223bb.png)

**Comment by lemanal** [comment]
@sarahsba @jtf621 @lemanal Could this text be shorter?
