### ISSUE TITLE
If random series of numbers are entered without street, app defaults to Leesville Rd

### ISSUE THREAD

**Issue by ncnwoko** [codefordurham/school-navigator#202]
![cfd-sn-defaultlocation](https://cloud.githubusercontent.com/assets/5464067/10403695/abfe1af4-6e9b-11e5-92fe-55e0629ed6cd.png)

**Comment by jtf621** [comment]
The result is not random, it will correspond to searching maps.google.com for "2348" + "Durham County"

The call to the geocoder call does not give user feedback on the actual address returned.

**Comment by copelco** [comment]
Related to #218

**Comment by jtf621** [comment]
Either #218 or #224 will alert the user to the issue.
