### ISSUE TITLE
Determine whether you are guaranteed a spot in a year-round schools if you apply.

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#203]

**Comment by NoOutlet** [comment]
You are not. From [District Policy 4133](http://www.dpsnc.net/pages/Durham_Public_Schools/District/About_DPS/District_Policies/Series_4000_-_Student_Services/4133)

> Assignment to a calendar magnet school (except for students whose base school is a calendar magnet ) will be determined through an application / lottery process that first takes into account any assignment priorities established by the Board of Education.
