### ISSUE TITLE
walk zone schools are disappearing

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#204]
When I enter an address within a walk zone or move the house icon inside a walk zone, the associated school disappears from the map.  RN Harris & Club Blv.

**Comment by NoOutlet** [comment]
It disappears from the map when you are on the Magnets tab because it becomes your assigned school. The concept is that schools in the Magnets tab required an application.

**Comment by jtf621** [comment]
see: http://dpsncapplication.com/site327.php

Q: What is a walk zone?
A: A walk zone is an assignment preference that allows automatic assignment to students who live within one (designated safe walking) half mile of the schools that have this preference. Burton Magnet, Club Blvd Magnet and R.N.Harris Magnet Elementary are the only schools that have this assignment preference. A walk zone is not part of the lottery. It acts as an attendance zone, providing automatic assignment throughout the school year.

**Comment by jtf621** [comment]
As you move the map icon, the assigned zones are changing and the app is updating the list.  see @NoOutlet comment
