### ISSUE TITLE
confusing use of "priority" for the magents

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#205]
We're using "priority" as a general term to refer to any magnet school where the entered address is in the priority, choice or walk zones.  But because "priority" is also the name of the name, this is confusing.  Instead of having "priority" appear, can we have "priority zone" "walk zone" or "choice zone" appear?

**Comment by jtf621** [comment]
discussed with @sarahsba and the current search page differentiates between "priority zone", "walk zone", "choice zone", "year round zone"
