### ISSUE TITLE
Usersnap - Maps do not appear on ipad

### ISSUE THREAD

**Issue by adamajm** [codefordurham/school-navigator#206]
**Comment**: Maps do not appear on ipad
[Open #20 in Usersnap Dashboard](https://usersnap.com/a/#/code-for-durham/p/school-navigator-38602a3a/20)

![Usersnap - Maps do not appear on ipad](https://usersnappublic.s3.amazonaws.com/2015-10-10/14-12/d5f17b1c-caf7-4b5d-a4c9-e6077bb2960e.png)

**Browser**: Safari 7 (iOS)
**Referer**: [https://schools.codefordurham.com/#/](https://schools.codefordurham.com/#/)
**IP**: 98.26.38.51
**Screen size**: 768 x 1024 **Browser size**: 768 x 928

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by victor-rocha** [comment]
works fine
