### ISSUE TITLE
Usersnap - Cannot select magnets or charters on ipad. Only get a pop up

### ISSUE THREAD

**Issue by adamajm** [codefordurham/school-navigator#207]
**Comment**: Cannot select magnets or charters on ipad. Only get a pop up
[Open #21 in Usersnap Dashboard](https://usersnap.com/a/#/code-for-durham/p/school-navigator-38602a3a/21)

![Usersnap - Cannot select magnets or charters on ipad. Only get a pop up](https://usersnappublic.s3.amazonaws.com/2015-10-10/14-13/8de96e02-ed99-467f-ad7a-bd6736265041.png)

**Browser**: Safari 7 (iOS)
**Referer**: [https://schools.codefordurham.com/#/?lat=35.9950478&lng=-78.90066259999998&addr=100%20main%20st](https://schools.codefordurham.com/#/?lat=35.9950478&lng=-78.90066259999998&addr=100%20main%20st)
**IP**: 98.26.38.51
**Screen size**: 768 x 1024 **Browser size**: 768 x 928

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by adamajm** [comment]
it takes a double tap to get to select on an ipad

**Comment by jtf621** [comment]
Double tap works to select
