### ISSUE TITLE
Usersnap - maps do not appear on OSX Safari

### ISSUE THREAD

**Issue by adamajm** [codefordurham/school-navigator#208]
[Open #22 in Usersnap Dashboard](https://usersnap.com/a/#/code-for-durham/p/school-navigator-38602a3a/22)

![Usersnap - maps do not appear on OSX Safari](https://usersnappublic.s3.amazonaws.com/2015-10-10/14-19/0760b6ac-4d91-40cc-ab66-7df70a95e19a.png)

**Browser**: Safari 7 (Mac OS X Mavericks)
**Referer**: [https://schools.codefordurham.com/#/?lat=35.9950478&lng=-78.90066259999998&addr=100%20main%20st](https://schools.codefordurham.com/#/?lat=35.9950478&lng=-78.90066259999998&addr=100%20main%20st)
**IP**: 98.26.38.51
**Screen size**: 1280 x 800 **Browser size**: 1148 x 648

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by lemanal** [comment]
Is this just like the other one you just closed, @victor-rocha ?

**Comment by jtf621** [comment]
Now it works with a small lag due to cache refreshing on mac OSX Safari
