### ISSUE TITLE
Usersnap - Legend - Change "District" to "Neighborhood"

### ISSUE THREAD

**Issue by adamajm** [codefordurham/school-navigator#214]
**Comment**: to align with other terminology?
[Open #28 in Usersnap Dashboard](https://usersnap.com/a/#/code-for-durham/p/school-navigator-38602a3a/28)

![Usersnap - Legend - Change "District" to "Neighborhood"](https://usersnappublic.s3.amazonaws.com/2015-10-10/16-39/9867e497-c63a-44fe-8f65-9e2cddb22830.png)

**Browser**: Chrome 45 (ChromeOS)
**Referer**: [https://schools.codefordurham.com/#/?lat=36.00868200000001&lng=-78.90558999999996&addr=1000%20n%20duke%20st](https://schools.codefordurham.com/#/?lat=36.00868200000001&lng=-78.90558999999996&addr=1000%20n%20duke%20st)
**IP**: 70.63.151.66
**Screen size**: 1366 x 768 **Browser size**: 1366 x 657

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by adamajm** [comment]
What's the difference between "District" and "Traditional Option"?

**Comment by NoOutlet** [comment]
District zone designates the default neighborhood school.
If a parent desires a year round school, they can apply to that school if their house is within that schools year round zone.
Sometimes a year round school *is* the default neighborhood school. In those cases, the parents can apply to a traditional calendar school if their house is within that schools traditional option zone.
