### ISSUE TITLE
Redesign layout for Navigating DPS page

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#233]
Feedback: Navigating DPS has far too much text at the first level. Each of these blurbs--neighborhood, magnet, charter, what is a walk zone, what is a priority zone, what is a choice zone--should have a one-sentence description and then a "learn more" button. Also, the categorization of these six things should be different: the first three are types of schools, the latter three are types of zones. Design should reflect that somehow.

Should get Julie's feedback on this.

**Comment by sarahsba** [comment]
James is working on this.  Does he have a profile on github?

**Comment by sarahsba** [comment]
@jruggiero32 has created a mock up for the Navigating DPS (now called School Guide) page.  See issue #269

**Comment by lemanal** [comment]
@sarahsba great. Can this ticket get closed if it's already covered elsewhere?
