### ISSUE TITLE
Improve explanations of magnet zones

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#234]
Create 1 sentence leading explanation of each type of zone.  Are they only relevant for elementary zones?  Add intro on the magnet page, there are 3 ways that you can end up in a magnet:....

Look at how DPS explains magnets on the magnet site; look at how Memphis explains magnets and Strong Durham Schools. Might need to get input from Chrissy.

**Comment by mianwu** [comment]
I am working on this.

**Comment by jtf621** [comment]
The Memphis site is http://memphisschoolguide.org/

**Comment by jtf621** [comment]
This link may be helpful http://www.dpsnc.net/pages/Durham_Public_Schools/District/About_DPS/District_Policies/Series_4000_-_Student_Services/4131

**Comment by sarahsba** [comment]
The revised School Guide page that @jruggiero32 created addresses this.  See #269 .  We can close this issue.
