### ISSUE TITLE
Replace 'x' in school list with ability to close out list view with a click on the school level bar.

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#236]
Enable ability to click on school level bar to open and close the view of that level (elementary etc) rather than having to click on the ‘x’

at least 1/3 of users in testing couldn't find the 'x' and tried to close the view by clicking on the bar.

**Comment by qkombur** [comment]
This [branch] (https://github.com/codefordurham/school-navigator/compare/issue-236
) implements the feedback  but there is some quirks that I still need to iron out. 

For instance clicking on a school's name will open up all the schools in the list.
Also once you close a school the others will stay open. Just to name a few.
