### ISSUE TITLE
Usersnap - magnet lottery admissions

### ISSUE THREAD

**Issue by adamajm** [codefordurham/school-navigator#239]
**Sender**: alicia_adrian@yahoo.com
**Comment**: this document is produced by DPS every year, it's likely part of the DPS School Board Meeting notes/minutes in Oct or Nov.  A friend send and said to distribute widely... I think it's an important piece of information when deciding how to complete the lottery form.  I would love to see something similar for charters, but i don't know that they have to provide applications vs acceptance numbers anywhere. I can ask my friend   where she got it, if you are interested.

https://drive.google.com/file/d/0BzNFoiws16FEa3A2WFlKdTBSbE0/view?pli=1
[Open #32 in Usersnap Dashboard](https://usersnap.com/a/#/code-for-durham/p/school-navigator-38602a3a/32)

![Usersnap - magnet lottery admissions](https://usersnappublic.s3.amazonaws.com/2015-11-22/00-20/8771f1fe-ec9d-4779-bb38-b57049599dc4.png)

**Browser**: Safari 9 (Macintosh)
**Referer**: [https://schools.codefordurham.com/#/navigating](https://schools.codefordurham.com/#/navigating)
**Screen size**: 1152 x 720 **Browser size**: 1152 x 598

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by lemanal** [comment]
@sarahsba Did you get survey data about people wanting access to lottery statistics?

**Comment by sarahsba** [comment]
This is awesome.  I've uploaded the pdf to the School Navigator google drive and emailed Alicia to find out where this information is posted.
