### ISSUE TITLE
Improve search engine optimization for site

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#240]
as part of this, we should consider giving the website a new url that is doesn't have code for durham in it and is easier for people to remember.

**Comment by lemanal** [comment]
@adamajm @copelco how does this request fit in with overall CfD branding?

**Comment by lemanal** [comment]
@adamajm @copelco  !!!

**Comment by jtf621** [comment]
@sarahsba @adamajm @copelco @lemanal 

We are now durhamschoolnavigator.org, is there any more to do, or can we close this out?

**Comment by jtf621** [comment]
We are now durhamschoolnavigator.org, please reopen any specific remaining issues
