### ISSUE TITLE
Include information about how to transfer

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#243]
Recommendation from survey: "HOW TO TRANSFER. Little known but powerful tool. You provide transportation you can go to basically any traditional school."  We should find out where this information exists on the DPS site and at least link to it on the Navigating DPS page.

**Comment by jtf621** [comment]
see #229

**Comment by arbianchi** [comment]
We suggest creating a new "Transfers" section in the School Guide and link to the following pages:

1) Process for applying for transfer:
https://durhamschoolnavigator.org/#/navigating/neighborhood

2) Application for Transfer forms:
http://durham.schoolwires.net/domain/107

3) Policies related to transportation, etc. for transfers:
http://www.dpsnc.net/site/default.aspx?PageType=3&DomainID=112&ModuleInstanceID=229&ViewID=047E6BE3-6D87-4130-8424-D8E4E9ED6C2A&RenderLoc=0&FlexDataID=268&PageID=262

For charter schools, there should be a link to the application page in /navigating/charter:
http://www.dpi.state.nc.us/charterschools/applications/
