### ISSUE TITLE
Edits for Sample Profile

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#247]
The sample profiles looks great.  I've made some tweaks in the attached doc - things in the google doc that were changed/added after creating the wireframe.  Sorry these weren't as clear as they should have been in the first round.  All changes are in red in the doc called Edits to Sample Profile: https://drive.google.com/drive/folders/0BzzdkaFnyRitcGhBQ0tmdi0yenc

**Comment by NoOutlet** [comment]
I just committed these edits in cc16b4a
