### ISSUE TITLE
Add website to the listview of schools on the admin page

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#249]
Hey Victor - could you do this?  It will make manually pulling info from the sites much easier. thanks! 

Add the website field and remove the photo field to the listview here: https://durhamschoolnavigator.org/admin/schools/school/

**Comment by jtf621** [comment]
@sarahsba is this still needed based on the school survey process of adding info to the school profile?

**Comment by jtf621** [comment]
superseded  by school profile
