### ISSUE TITLE
Determine whether one of the W.G. Pearson entries should be deleted

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#251]
W.G. Pearson IS LISTED 2X and it looks like the school may be closed entirely.  Determine whether school is still operating as a magnet or a neighborhood school, and delete the other.

**Comment by jtf621** [comment]
Looks like it is now a Magnet Elementary  http://pearson.dpsnc.net/pages/Pearson_Magnet_Elementary.

The middle school is set to inactive and will not show up in the site.

**Comment by jtf621** [comment]
Fixed type to magnet 

see http://www.dpsnc.net/pages/Durham_Public_Schools/Parent_Resources/CIA/Magnet_Schools/School_Informtion/Elementary_Schools/W__G__Pearson_STEAM_and_GT_Ele
