### ISSUE TITLE
Usersnap - 13131

### ISSUE THREAD

**Issue by adamajm** [codefordurham/school-navigator#253]
**Sender**: None
**Comment**: wdew
[Open #33 in Usersnap Dashboard](https://usersnap.com/a/#/code-for-durham/p/school-navigator-38602a3a/33)
**Notes**:
 - (1) rggrsg srfg es

![Usersnap - 13131](https://usersnappublic.s3.amazonaws.com/2016-03-09/20-36/e2ebbd51-2c58-4367-8ee6-ea1bcd0a8c5d.png)

**Browser**: Firefox 44 (Windows 8.1)
**Referer**: [https://durhamschoolnavigator.org/#/navigating](https://durhamschoolnavigator.org/#/navigating)
**Screen size**: 1366 x 768 **Browser size**: 1366 x 610

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jtf621** [comment]
Not clear on the issue.  Please reopen with more details.
