### ISSUE TITLE
Usersnap - The lunch and breakfast section might include the option of specifying tha[...]

### ISSUE THREAD

**Issue by adamajm** [codefordurham/school-navigator#256]
**Sender**: miranda.l.freeman@gmail.com
**Comment**: The lunch and breakfast section might include the option of specifying that a free and reduced lunch program exists, or that breakfast is free to all students. 
[Open #35 in Usersnap Dashboard](https://usersnap.com/a/#/code-for-durham/p/school-navigator-38602a3a/35)

![Usersnap - The lunch and breakfast section might include the option of specifying tha(...)](https://usersnappublic.s3.amazonaws.com/2016-03-17/22-22/0aae6e6d-482f-4f6c-86b5-fc9aef6a0095.png)

**Browser**: Safari 9 (iOS)
**Referer**: [https://durhamschoolnavigator.org/#/school/206/](https://durhamschoolnavigator.org/#/school/206/)
**Screen size**: 768 x 1024 **Browser size**: 1077 x 766

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jtf621** [comment]
Implemented in the profile and survey
