### ISSUE TITLE
Improve opening and closing mini profiles

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#257]
On homepage: https://durhamschoolnavigator.org/#/
When a school is selected and the mini-profile is open, getting back to the list view is difficult. Currently, you must click again on the Title for that school to get to the list. Goal would be to enable ability to click elsewhere to close the mini-profile - for example, on the title of the Grade Category (e.g. Elementary) or the school type category (e.g. Charter).

MINI-Profile VIEW
![image](https://cloud.githubusercontent.com/assets/8593748/15695174/7d7aaf90-2772-11e6-8fbe-531e0c04ad1e.png)

LIST VIEW
![image](https://cloud.githubusercontent.com/assets/8593748/15695189/a90854aa-2772-11e6-97a7-3db4f6b70c6a.png)

**Comment by elynch** [comment]
UX suggestion: instead of hiding the blurbs of the school when showing the mini-profile, still show the school names. This way the user can still see the list of available schools without having to close the mini-profile.

**Comment by elynch** [comment]
Worked with @RolfBates, and decided to remove the hide option when opening the school mini-profile. This way parents can still see the other school names while reading the mini-profile:

<img width="508" alt="screen shot 2016-06-14 at 8 15 51 pm" src="https://cloud.githubusercontent.com/assets/295842/16064187/e173d9c2-326c-11e6-94d7-01d858d6a279.png">

**Comment by sarahsba** [comment]
Great idea.

**Comment by alexlemann** [comment]
closing this out. thanks again @elynch
