### ISSUE TITLE
Usersnap - Bug with viewing school names

### ISSUE THREAD

**Issue by adamajm** [codefordurham/school-navigator#258]
**Sender**: sarah.sba@gmail.com
**Comment**: If I click into a mini profile under Charters and then click "Magnets" or "Neighborhood" without first clicking out of the mini profile view, I can't see any of the schools under Magnet or Neighborhood.
[Open #36 in Usersnap Dashboard](https://usersnap.com/a/#/code-for-durham/p/school-navigator-38602a3a/36)

![Usersnap - Bug with viewing school names](https://usersnappublic.s3.amazonaws.com/2016-03-19/03-19/c8769702-baac-46dc-8ace-77d6b7d27927.png)

**Browser**: Chrome 48 (Windows 7)
**Referer**: [https://durhamschoolnavigator.org/#/?lat=36.00868200000001&lng=-78.90558999999996&addr=1000%20North%20Duke%20St](https://durhamschoolnavigator.org/#/?lat=36.00868200000001&lng=-78.90558999999996&addr=1000%20North%20Duke%20St)
**Screen size**: 1366 x 768 **Browser size**: 1079 x 655

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by lemanal** [comment]
This is working for me. Are you still seeing it @sarahsba ? I'm going to close this for now. Please try it again and reopen if needed.

**Comment by sarahsba** [comment]
yep, it looks like it's fixed.
