### ISSUE TITLE
Link full profiles to mini profiles in map view

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#259]
Replace school website in mini profile with a hyperlink to "View school profile" and have the profile open in a new tab.  Julie Grundy (our design expert) also recommended having the school name link to the profile if clicked. We may also want to enable a link to the profile when you click on the school's icon on the map.

**Comment by sarahsba** [comment]
This is a UI issue.  @basiacoulter or @bendte, would either of you be interested in working on this?

**Comment by sarahsba** [comment]
Just discussed with @basiacoulter, and her recommendation is to add  "See full profile" as a hyperlink to the profile on its own separate line to the bottom of the mini profile for each school.  This is a change to the mini profile in the map view.

![image](https://cloud.githubusercontent.com/assets/12042430/16436337/17e7d96e-3d6b-11e6-94eb-31aa58c2348c.png)

**Comment by jtf621** [comment]
fixed in pr #350
