### ISSUE TITLE
Recommended Changes to the Profile

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#263]
Based on feedback from school administrators and design professional: tracked changes in the google drive: Sample School Profile Edits v2 https://drive.google.com/drive/folders/0BzzdkaFnyRitcGhBQ0tmdi0yenc

**Comment by jtf621** [comment]
@sarahsba can we close this based on the profile work that was done over the last 2 weeks and the need for specific feedback on the implementation now?

**Comment by jtf621** [comment]
profile is implemented.  Please reopen any specific issues that are in production.
