### ISSUE TITLE
Update School Guide page

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#269]
use this template to update the School Guide page: https://durhamschoolnavigator.org/#/navigating

[Navigating Durham Schools - About Page v2.pptx](https://github.com/codefordurham/school-navigator/files/220313/Navigating.Durham.Schools.-.About.Page.v2.pptx)

**Comment by lemanal** [comment]
@sarahsba is this ready to be implemented?

**Comment by sarahsba** [comment]
yes.

**Comment by sarahsba** [comment]
@lemanal and @jtf621 - can we add this to the list of civic hack day tasks?

**Comment by lemanal** [comment]
@sarahsba sure. Added it to the milestone.

**Comment by alexlemann** [comment]
![screen shot 2016-06-04 at 1 07 59 pm](https://cloud.githubusercontent.com/assets/46069/15800969/70ff1e14-2a55-11e6-8ad0-d428ad37fce3.png)

Here's Navigating Durham Schools - About Page v2.pptx as an image so other people without powerpoint can see it

**Comment by ammraleigh** [comment]
Hey. 
I made the requested changes. 
However I meant to push the update to a branch for review but by mistake it went on master. 
How would you like to handle this? 
Want me to put back the original and then correctly put it the changes on a branch? 
Ann

**Comment by ammraleigh** [comment]
Checked by Victor! Ship it.

**Comment by sarahsba** [comment]
Looks good @ammraleigh!  

2 comments: Can we delete the "My Assignments" line at the bottom of the page?  Also, for the "view schools" in the top line, only the charter column has a hyperlink.  Can we add a hyperlink for neighborhood and magnet, or do these pages need to be created?

**Comment by ammraleigh** [comment]
Hi!

These recommended changes were already done last night:
  - removed row  "My Assignments"
  - fix links to "View Schools" for Assigned and Magnet

However these changes will not show up on the public version until the next
release is put out.

**Comment by sarahsba** [comment]
Great, thanks!
