### ISSUE TITLE
Setup Amazon SES for email

### ISSUE THREAD

**Issue by lemanal** [codefordurham/school-navigator#273]

**Comment by lemanal** [comment]
Emails are working! Yay! @copelco , will we get errors about bounced emails etc?

**Comment by copelco** [comment]
Bounces are now sent to our group email address

**Comment by copelco** [comment]
Maybe we should lock down the google group..

**Comment by lemanal** [comment]
The group only allows members to read posts. Let's leave it that way and close this out. Sound good @copelco ?
