### ISSUE TITLE
QA & Testing placeholder

### ISSUE THREAD

**Issue by lemanal** [codefordurham/school-navigator#274]

**Comment by lemanal** [comment]
Test:
* Create survey
* Send survey
* Resend survey

**Comment by jtf621** [comment]
I have done all three for school/247 and it was working by 9:30 tonight. 

Let’s get a second look for another school now that it is working.  (keep active=False to prevent it from showing in the map interface)

**Comment by jtf621** [comment]
I looked at the School profile and survey with fresh eyes and added issues:
- #284
- #285
- #286
- #287
- #288
- #289
- #290
- #291
- #292
- #293

**Comment by lemanal** [comment]
There have been lots of eyes on Phase 2. Closing this out. Add more specific tickets as needed.
