### ISSUE TITLE
Make sure POST API calls don't allow editing models

### ISSUE THREAD

**Issue by lemanal** [codefordurham/school-navigator#277]
Models can only be changed by forms not API

**Comment by lemanal** [comment]
@jtf621:
Set the policy
http://www.django-rest-framework.org/api-guide/permissions/#setting-the-permission-policy
To IsAdminUser
http://www.django-rest-framework.org/api-guide/permissions/#isadminuser

**Comment by jtf621** [comment]
fixed in 2476194af137b27c13377b526b60ae9677bab105

**Comment by lemanal** [comment]
c4e056d2df703a922e7f8ac470323d5f1221da02

**Comment by lemanal** [comment]
@jtf621 Not seeing this.

**Comment by lemanal** [comment]
LTGM Thanks @jtf621
