### ISSUE TITLE
make lottery_deadline widget a date picker in the survey

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#284]

**Comment by drumslayert** [comment]
I'll grab this issue

**Comment by jtf621** [comment]
@drumslayert see https://durhamschoolnavigator.org/survey_form/jnVKv0xgly/ for a sample form.

**Comment by lemanal** [comment]
@drumslayert do you have an update on this issue?

**Comment by jtf621** [comment]
@drumslayert do you have an update on this issue?

**Comment by jtf621** [comment]
@victor-rocha it looks like @drumslayert is not on this anymore.  Can you give me a pointer on implementation so we can get the Charter schools survey out soon?
