### ISSUE TITLE
Implement State Report Card url for each school in school profile

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#287]
`To view the state report card for this school, click here.` link should point to most recent available school report card for each school.

**Comment by sarahsba** [comment]
@jtf621 - could we ask ppl to collect a list of all the state report card links at civic day of hacking?  Let me know and I can add more detail to this.

**Comment by RolfBates** [comment]
Is [this the homepage](http://www.ncpublicschools.org/src/) for the report cards? They link out to a [flash web app here](https://ncreportcards.ondemand.sas.com/landing.html). I'm not finding any url/query parameters to link directly to a specific school in that web app. Is there another way to access the data?

**Comment by RolfBates** [comment]
Nevermind, I found a pdf version with a unique url. (Example here)[https://ncreportcards.ondemand.sas.com/snapshots/740302_2015_K-8-School.pdf].

**Comment by sarahsba** [comment]
Thanks @RolfBates.  Will we need to manually update this for each school every year?

**Comment by RolfBates** [comment]
Yeah, unfortunately it seems that way. The rest of the pieces of the URL are uniform, but they use the North Carolina school code, which are not currently stored in the db. I'm getting those together in a migration. Then, we can construct the url with [ng-href](https://docs.angularjs.org/api/ng/directive/ngHref) on the front end, and plug in the most recent year as a string literal.

**Comment by sarahsba** [comment]
Sounds good.  Thanks for working on this!

**Comment by RolfBates** [comment]
Here is my working notes for the proprietary id to state id mapping: [schools.txt](https://github.com/codefordurham/school-navigator/files/315242/schools.txt)

**Comment by jtf621** [comment]
@RolfBates 

I was testing the site and the implementation shows unavailable more frequently than I expected.  It looks like the state_id is on the school profile not on the school.  The result is that when a new survey is sent out, the state_id is null. Can you take a look at this again?

**Comment by alexlemann** [comment]
@lotusgraham here's another ticket that might be interesting.... but has some history

**Comment by alexlemann** [comment]
@JonathanFrederick
