### ISSUE TITLE
Make urls embedded in survey responses clickable on school profile page

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#291]

**Comment by lemanal** [comment]
@copelco suggests rendering the field with markdown

**Comment by victor-rocha** [comment]
what fields would need markdown?

**Comment by jtf621** [comment]
I suggest: mission_statement, transportation_explanation, breakfast_explanation, lunch_explanation, extended_care_financial_assistance, & parental_involvement_notes

**Comment by lemanal** [comment]
Markdown was just a quick way of possibly fix this. It might introduce other problems like confusion when people accidentally use some markdown scripts.
Not sure if linky would do instead.

**Comment by lemanal** [comment]
@gturmel https://docs.angularjs.org/api/ngSanitize/filter/linky

**Comment by gturmel** [comment]
I've added the linky filter to the fields that jtf621 recommended. It works, but it's also throwing some serious errors in the console.

**Comment by jtf621** [comment]
@gturmel do you have an update on this issue?

**Comment by jtf621** [comment]
This is complete in master
