### ISSUE TITLE
Preserve line breaks in long survey text responses on school profile

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#292]
for example mission statement, principal bio are long enough should have <p> tags possible

**Comment by lemanal** [comment]
Maybe https://docs.djangoproject.com/en/1.9/ref/templates/builtins/#linebreaksbr ?

**Comment by jtf621** [comment]
@victor-rocha I am getting errors using the angular $sce.trustAsHtml approach you found.  Let's talk it through next chance we get.

**Comment by jtf621** [comment]
I think I got it see pull request

**Comment by jtf621** [comment]
fixed via 217d9849d3e1
