### ISSUE TITLE
open school website in separate tab

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#295]
On the schools page (https://durhamschoolnavigator.org/#/schools), can we make the school website open up on a separate tab when you click on the school name?  Right now it opens up in the same tab and so takes you away from School Navigator.

**Comment by victor-rocha** [comment]
The issue is that it takes you to the shcool website, this should take you to the school profile instead.

**Comment by sarahsba** [comment]
agree that taking you to the profile instead of the school website would be ideal.  either way, though, it should open in a separate tab.

**Comment by victor-rocha** [comment]
I hate websites that open new tabs when you click on things (unless is absolutely neccessary). Are you sure you want to open a new tab and increase the number of open tabs on our users browser?

**Comment by sarahsba** [comment]
sure, if it's the school profile which is still part of our site, i don't think it needs to be opened in a new tab.

**Comment by victor-rocha** [comment]
cool
