### ISSUE TITLE
Final profile suggested edits

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#299]
This looks great!  I love what you did with the "coming soon" for the teacher satisfaction data.  Here are a few final minor edits:

- Free and Reduced Lunch/Breakfast: if a school selects "No", the profile should read, "This school does not participate..." Right now it reads, "This school does not participateS.."

- Extended Care: Can we use the following responses: 
          If YES to before and after care: "This school offers before and after care."
         If YES to before and NO to after: "This school offers before care and does not offer after care."
         If NO to before and YES to after: "This school offers after care and does not offer before care."

- Targeted Academic Offerings: change, "Staff and additional resources that you have for" to "Staff and additional resources provided for:"  

- Targeted Academic Offerings:
      Change "Your Academic Theme" to "Our Theme"
      Change "Exceptional Children" to "Special Education (Exceptional Children)"

- Parent Involvement: Add PTO to "Learn more about this school's PTA/PTO"

- Reflections: Change to "Testimonials" (based on feedback from DPS and parents)

**Comment by victor-rocha** [comment]
@sarahsba missing the message for when the school doesn't offer neither before nor after care

**Comment by jtf621** [comment]
try: This school does not offer before or after care.

**Comment by victor-rocha** [comment]
I didn't see your comment until now... I coded "This school does not offer extended care."

**Comment by jtf621** [comment]
OK
