### ISSUE TITLE
Find principal email addresses on school websites

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#300]
look at school websites to find  email addresses and names of principals for all neighborhood and magnet schools.  Put in google spreadsheet here: https://docs.google.com/spreadsheets/d/1gr02srutkAGRPPLaiTMnD32hiAmDVklEPB7mOABOh4M/edit#gid=0

**Comment by sarahsba** [comment]
We have most of the charter ones.  Will need to look up the remaining charters manually.

I don’t have all the principals but do have most ( missing KIPP Durham, Healthy Start and Research Triangle Academy):

Agatha Brown <info@globalscholarsacademy.org>, 
Yvette Munroe <yvette.munroe@theidylschool.org>, 
Pamela Blizzard <pblizzard@rthighschool.org>, 
Jennifer Lucas <jlucas@voyageracademy.net>, 
Cynthia Gadol <cgadol@excelsiorca.org>, 
Mark Tracy <tracy@kestrelheights.org>,
Ben Adams <badams@kippenc.org>, 
Tiffany Grant <Tiffany@cpsfc.org>, 
Mckoy Thomas <tmckoy@reachingallminds.com>
Gail Taylor <gailtaylor@carterschool.org>, 
Mark Bailey <mbailey@joycharter.org>
Heffernan John <john@cpsfc.org>

**Comment by BobbyBarbeau** [comment]
https://docs.google.com/spreadsheets/d/1QSeW_IdPB1nqrpunq_GOFyK2UYll1yCax0PBfTgiCiA/edit?usp=sharing

Sheet2 in the above spreadsheet contains school names, urls, principal names, and email addresses. 

I was *not* able to do this programmatically as I'd hoped; the "About Us" page for each school was easy enough to generate URLs for. However, the actual data was contained in a frame, whose URL was not easily hackable (contained unique numeric identifiers, etc.). 

So I grabbed the data manually. It's completed, but not easily reproducible. 

I also have other information from the About Us page, e.g. enrollment, hours of operation, assistant principal/email (when available), etc. This is located in Sheet3, but needs to be combined into sheet 2. 

Also, some principals were listed but did not have email addresses. Those remain NAs, but the email account naming convention seems to be firstname.lastname@dpsnc.net. I wanted to populate email address with this "guess", but haven't done so yet.

**Comment by BobbyBarbeau** [comment]
The spreadsheet I linked should still be available and has some extra data from the "About Us" page, but I did go ahead and add the requested data to the original doc.

**Comment by sarahsba** [comment]
Bobby - Awesome work on pulling all of the principal emails!!  This makes
it possible for us to send out the survey to all of the DPS schools.  Thank
you!

**Comment by alexlemann** [comment]
@sarahsba @npage915 can this get closed out?

**Comment by sarahsba** [comment]
Yes.
