### ISSUE TITLE
Separate Elementary & Middle Central Park School for Children Charter into 2 schools

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#305]
Right now, CPSC is listed as a single schools, but it's actually 2.  We need to create 2 separate profiles, one for the elementary and one for the middle school:

1. Central Park School for Children (Elementary): 
Address: 724 Foster Street, Durham, NC 27701
Grades: K-4
Principal Email: john@cpsfc.org

2. Central Park School for Children (Middle): 
Address: 121 Hunt Street, Durham, NC 27701
Grades: 5-8
Principal Email: john@cpsfc.org

**Comment by sarahsba** [comment]
HOLD on this for now.  We've realized this is an issue for several of the charters and are following up with the Collaborative to get their input before proceeding further.

**Comment by jtf621** [comment]
Fixed in #321
