### ISSUE TITLE
Add Research Triangle High School to the School and School Profile databases

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#306]
**Need to get admin access to durhamschoolnavigator.org in order to complete this task.**

We are currently missing Research Triangle High School.  It is DIFFERENT from Research Triangle Charter Academy.

#School Page
School Name: Research Triangle High School
School Type: Charter
Address: 3106 E. NC54, Research Triangle Park, NC 27709
Principal email: pblizzard@rthighschool.org

#School Profile
Level: High
Grades: 9-12
website: http://www.researchtrianglehighschool.org/
School hours: 9:00 a.m. – 3:45 p.m.
Mission: The mission of Research Triangle High School is to increase access to globally competitive Science, Technology, Engineering, and Math (STEM) education for students and teachers across North Carolina, by incubating, proving and scaling innovative models of teaching and learning.

All the fields in this spreadsheet should ideally be completed for this school: https://docs.google.com/spreadsheets/d/1E6ChD5RCSQH8LTuavGTqhe3He4NkNgsZB-lXOQkpqOU/edit#gid=0

**Comment by sarahsba** [comment]
@npage915 - can you work on this along with the other charter schools?

**Comment by npage915** [comment]
Added under RTHS
