### ISSUE TITLE
Update survey email so it works with charters

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#308]
Discuss with Jeremy & Alex whether we can create 2 separate emails for charter and district since intro to each will be different.  Perhaps it's just an intro line that differs by school type?

**Comment by jtf621** [comment]
@sarahsba please write the copy for the Charter school email.

**Comment by sarahsba** [comment]
See email for charters here: https://docs.google.com/document/d/1rJZSTtX2x12rB0RRceC0PIVBRGMl6jFoxYvTAKGANds/edit

We should use this as the survey email for now and can swap it out when we send it to the districts.

**Comment by jtf621** [comment]
duplicate of #318.  fixed in that issue and pull request #319.
