### ISSUE TITLE
Create generic email ID that will go to someone on the School Navigator team

### ISSUE THREAD

**Issue by npage915** [codefordurham/school-navigator#314]
It would be useful to have generic email ID (e.g. schoolnavigatorteam@gmail.com) that multiple folks could have access to for when principals have questions in creating/updating their profiles in the longer term. This will enable a generic email blast to be used without having to continuously update the language if there are fluctuations in team members.

**Comment by npage915** [comment]
I just created the following address:

email: schoolnavigatorteam@gmail.com
pw: SchoolNavigator

We can discuss how to link to site on Tuesday

**Comment by alexlemann** [comment]
@npage915 These comments are public and stored in lots of people's email accounts. Can you change the password and we can share it in person on Tuesday?

**Comment by npage915** [comment]
Done - apologies!
