### ISSUE TITLE
Incorrect grade level info for School for Creative Studies

### ISSUE THREAD

**Issue by schpatel** [codefordurham/school-navigator#317]
The school navigator website reflects that the School for Creative Studies spans grades 6 - 10 while the actual site for the school indicates that it spans grades 6 - 12.

https://durhamschoolnavigator.org/#/school/218/

http://scs.dpsnc.net/pages/School_for_Creative_Studies

**Comment by jtf621** [comment]
This can be fixed in the admin if you have permission.  The SchoolProfile is the place to update the data.

**Comment by sarahsba** [comment]
Fixed the grade levels in the school profile for School for Creative Studies.
