### ISSUE TITLE
Create New Email Template for Charters & Change Salutation in Survey Email

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#318]
Currently, the salutation in the survey email reads "Dear [Principal Name]."  Since we are now sending the email to the principal OR superintendent (the latter in the case of the 3 charters that have schools within schools), we need to update this field [Principal Name] to the more generic [School Name] so that the salutation reads, "Dear [School Name] Team."

**Comment by BobbyBarbeau** [comment]
See https://github.com/codefordurham/school-navigator/pull/319 for the charter template file. 

Hopefully I did this right...? Still getting used to github!
