### ISSUE TITLE
In admin separate Voyager, Kestrel, and Central Park School into Elementary, Middle, High as appropriate

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#321]
In admin separate Voyager, Kestrel, and Central Park School into individual Elementary, Middle, High schools as appropriate to resolve the below issue.

SCHOOLS AT ISSUE
Voyager Academy (k-12) - separate locations and principals
Kestrel Heights (k-12) - separate principals, same location
Central Park School for Children (k-8) - separate locations and principals

paraphrasing @sarahsba email

Hey team,
Get ready for a long email:

@npage915 and @sarahsba realized at the last meeting that 3 of them are essentially several schools under 1 name.  The elementary and middle schools, for instance, have different principals, start times, locations, and offerings.  Given these distinctions, it would be difficult to represent them with a single profile, so we recommend having 1 profile per principal.  This means that that Central Park School for Children, which has separate principals for its elementary and middle schools, would have a profile for the elementary school and another for its middle school while Maureen Joy,  with one principal overseeing the entire school, would have a single profile.

Below are further thoughts and implications of this which we can discuss on Tues:

Possible characteristics to determine # of profiles
School name
Principal (our vote)
Location
Website
Superintendent preference
Expansion of seats in the lottery (i.e. not just replacing kids who have left)
 
SCHOOLS AT ISSUE
Voyager Academy (k-12) - separate locations and principals
Kestrel Heights (k-12) - separate principals, same location
Central Park School for Children (k-8) - separate locations and principals

**Comment by jtf621** [comment]
@npage915 @jtf621 @sarahsba discussed in detail tonight and decided on the above approach for now.

**Comment by npage915** [comment]
Updated to reflect appropriate breakdowns of school
