### ISSUE TITLE
List of Charters on Schools List page. Remove outdated charters specific page

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#330]
This list of charters is incomplete and seems to contain a few errors (eg Kestrel is with an "e" not "a"; Idyl school shouldn't be included).  https://durhamschoolnavigator.org/#/navigating/charter

Can we build this page so that it pulls the school names from the Schools database?  And can we pull in the application information from the school profile database so that it remains updated?  It looks like the descriptions here are a manual entry.

@alexlemann - do you know who worked on this page?

**Comment by alexlemann** [comment]
@sarahsba apparently I did.... What do you think about adding a filter to the schools list page that is for charters and removing this page?
https://durhamschoolnavigator.org/#/schools

**Comment by alexlemann** [comment]
@npage915 and @victor-rocha said yes to ^^^

**Comment by sarahsba** [comment]
agreed, that's great.

**Comment by alexlemann** [comment]
Thanks @JonathanFrederick. This is also related to #331.
