### ISSUE TITLE
School for Creative Studies not appearing in the map view list

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#332]
The School for Creative Studies is a 6-12th grade magnet that is categorized as "secondary."  However, does not appear anywhere in the map list view.  Is this because it is a calendar magnet that is only an option for certain locations in Durham (and therefore wouldn't appear when I search for schools for 1000 N Duke St)?  Or is this a bug?

 
![image](https://cloud.githubusercontent.com/assets/12042430/16096369/a47f6b44-3316-11e6-88b2-daeda96571ad.png)

**Comment by jtf621** [comment]
Sarah, Can you login to the admin and see if the school is listed and is active?

**Comment by jtf621** [comment]
@sarahsba The school for creative studies has a zone that you need to be in to attend.  

Enter 3000 Roxboro Rd to see it.

**Comment by sarahsba** [comment]
Thanks Jeremy.
