### ISSUE TITLE
update DPS email template

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#333]
Need to rewrite the references to the May meeting that did not happen.

**Comment by jtf621** [comment]
@sarahsba or @npage915 can you look at /templates/survey_email_dps.txt

**Comment by sarahsba** [comment]
Yes.  It probably makes sense to wait on this until we hear back from
Chrissy and know how we're communicating with the principals.  Does that
work?

**Comment by jtf621** [comment]
Yes waiting is ok. I just wanted to Document  that this was needed while I was touching the code.

**Comment by jtf621** [comment]
@RolfBates can you work with @npage915 on this?
