### ISSUE TITLE
Add picture question to school profile survey

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#335]
Add a "Picture" header with the following questions to the end of the survey, before the feedback question.	

**Picture**
Please upload a picture of your school building as a jpeg file here.  This picture will be showcased at the top of your school's profile.

[add button/function to upload a picture]

**Comment by jtf621** [comment]
@sarahsba @victor-rocha  are you OK if we have them email the picture for Phase 2 and make the upload a Phase 2.5 issue? 

I can implement the email easily and get the charters going, but would need some help with the upload issue.

**Comment by sarahsba** [comment]
yes, I defer to @jtf621 and @victor-rocha on this.

**Comment by sarahsba** [comment]
If we're receiving the photos by email now, do we want to revert back to this language:

Picture
We expect the vast majority of profiles will include a picture of the school building.  Do you want to update/add a picture to your school's profile?
[Dropdown - Yes/No]
 
If you selected "Yes," please send a jpg of the photo to [email ID] with the subject line: Picture for [School Name].
