### ISSUE TITLE
Change "Principal Email" field in Schools Database to "Principal/Superintendent Email"

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#339]
The addition of "Superintendent" reflects the fact that, for some of the charters that contain multiple schools under the same name, we will send the email to the superintendent who will then be responsible for determining the best way to complete the survey for each of their schools.

For ex, Central Park has 2 schools, a middle and elementary school, each with their own principal but with a single superintendent.  The superintendent will get the email for both of the schools.

HOWEVER, the principal name field will remain as the "principal name" only.

**Comment by alexlemann** [comment]
@lotusgraham check out the principal_name field here: https://github.com/codefordurham/school-navigator/blob/master/schools/models.py#L221
