### ISSUE TITLE
Before/after school survey answer not showing up properly on web page

### ISSUE THREAD

**Issue by npage915** [codefordurham/school-navigator#348]
Kestrel Heights Elementary School has entered "No" for both the before and after care options in the survey, but on the profile, it says that the school offers these servicess. (https://durhamschoolnavigator.org/#/school/252/) Might there be an issue of translating survey answer to profile here?

**Comment by victor-rocha** [comment]
Thanks for reporting this, I will look into this tonight.

**Comment by jtf621** [comment]
@victor-rocha did you find out what the issue is?  Need help?

**Comment by victor-rocha** [comment]
@jtf621 I did

**Comment by npage915** [comment]
Perfect - thank you for taking care of this, Victor! I will follow up with
Dr. Webb.
