### ISSUE TITLE
Update second paragraph of follow-up email to reflect ability for schools to upload photos

### ISSUE THREAD

**Issue by npage915** [codefordurham/school-navigator#353]
NOTE: The rest of the email should remain the same - this is the second paragraph. (Let me know if there's a better way to present the requested change.) Additionally, after the email goes out on 7/26, we should remove the line so it could be reused in future iterations and this feature will no longer be new/worth calling out. 

We would like to create a great profile for [school name], but we need your help. We ask that you and your team complete the survey below as soon as possible so we can include your school's completed profile on the site. We are also excited to share that schools are now able to upload photos directly through the survey, rather than emailing our team! Please see below for the survey link and further instructions.

**Comment by alexlemann** [comment]
Also, include updated email addr per #322
