### ISSUE TITLE
Open profile in new tab

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#354]
When you click on the "View school profile" link on the map page, it opens up the profile on the same tab so that you lose the map view.  I think it'd be easier for users if the profile opened in a separate tab so that users can open multiple profiles at a single time to read. If we do that, we'd want the mini-profile to remain open I think.  Right now if you hold control and click the "view school profile" link to open the profile in a new tab, the mini profile automatically closes and is no longer visible.

What do y'all think?  Maybe you discussed this already at the meeting in which case you can ignore this. :)

**Comment by alexlemann** [comment]
Hi @sarahsba I think that we discussed this in: #295 and decided that the links within the site would be in the same tab but links out to other sites would be in a new tab. Do you agree?

That said.... the link to the school's own site within the profile links out in the same tab now which is inconsistent with how this is handled in the mini profile view.

**Comment by sarahsba** [comment]
@alexlemann, you're right, we did agree to that in @295. I don't follow the second part of your comment: "That said.... the link to the school's own site within the profile links out in the same tab now which is inconsistent with how this is handled in the mini profile view." Can you elaborate?

**Comment by alexlemann** [comment]
@sarahsba I was talking about the school website link in the At A Glance section of the profile opening in the same tab even though it links out to a different site.
![at-a-glance-link](https://cloud.githubusercontent.com/assets/46069/17553934/6c9015bc-5ed6-11e6-8502-fbddb914c026.png)

**Comment by lotusgraham** [comment]
@sarahsba @alexlemann Below is a GIF of what these pages should behave like. I'll work on making this happen.

![schoolnav-newtab](https://cloud.githubusercontent.com/assets/13974084/17644628/b0464576-6159-11e6-9a27-1437531c1ede.gif)

**Comment by sarahsba** [comment]
Got it, thanks. I agree with the approach y'all are working on. Looks great.
