### ISSUE TITLE
Merrick-Moore Elementary School unable to save info

### ISSUE THREAD

**Issue by npage915** [codefordurham/school-navigator#358]
We received the below message from a principal who was unable to save his info. Can you please look into this and let me know if you think it's a School Navigator issue or something internal on his computer? 

"Good Evening,
I just tried to complete the survey for Merrick-Moore Elementary School.  I opened the page yesterday, completed the information today and tried to save.  When saving, I was directed to a page that said “Not Found.”  None of my information was saved.  How should I proceed before tomorrow’s deadline?
Thank you, Matt"

**Comment by victor-rocha** [comment]
Thanks for the heads up. I will make some time in a little bit to look at this.

**Comment by jtf621** [comment]
Thanks victor. I am not able to work this for 2weeks

**Comment by jtf621** [comment]
@victor-rocha @npage915 is this fixed?

**Comment by npage915** [comment]
Yes - this has been addressed.
