### ISSUE TITLE
Add color field to schools in database

### ISSUE THREAD

**Issue by jaycee** [codefordurham/school-navigator#36]
The school model should have a color field, which stores the color hex code (e.g. `#ffffff`). This should be returned via the API to the front end.

We might want to update the `loadschools` management command to assign initial colors when its run, or create a default colors fixture.

**Comment by lemanal** [comment]
Is this still needed @victor-rocha ?

**Comment by lemanal** [comment]
This isn't needed on the backend. Coloring schools will be done on the frontend. CC: @victor-rocha
