### ISSUE TITLE
Check status of overdue school surveys

### ISSUE THREAD

**Issue by brownap04** [codefordurham/school-navigator#365]
Going through school surveys for which status is currently "Over due" to assess what is missing from the surveys, and also which surveys may be in acceptable state.

Summary here: https://docs.google.com/spreadsheets/d/1yAfqbC7H6Yjm2FA2A4OQtpQ0EANWNHArdwyxJk02WVQ/edit?usp=sharing

**Comment by brownap04** [comment]
Summary of schools with status "Over due" is complete. Please let me know if you need anything else.

**Comment by jtf621** [comment]
Thanks Alice

**Comment by alexlemann** [comment]
This report has been automated now and prepping to send out reports to administrators. We're getting ready to send out surveys again. Thanks again @brownap04 and @jtf621
