### ISSUE TITLE
Add linkey filter to details.html

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#383]
Based on feedback from School for Creative studies profile. 

Test it on https://durhamschoolnavigator.org/#/school/218/
- Academically & Intellectually Gifted:  {{ school.profile.gifted_education }}
- Our Theme: {{ school.profile.other_academic }}
- data-ng-show="school.profile.points_of_pride1" {{ school.profile.points_of_pride1 }}
- data-ng-show="school.profile.points_of_pride2" {{ school.profile.points_of_pride2 }}
- data-ng-show="school.profile.points_of_pride3" {{ school.profile.points_of_pride3 }}

**Comment by alexlemann** [comment]
Fixed in #429. Thanks again @b-r-broge .
