### ISSUE TITLE
Correct incorrect information on the Sandy Ridge profile

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#391]
Our point of contact at Sandy Ridge sent me the attached corrections to their profile.  She has been an advocate of the site, and we don't want to lose her.  It'd be great if someone could make these changes asap.

![image](https://cloud.githubusercontent.com/assets/12042430/21413311/4bca8c84-c7c4-11e6-9d8f-e5bce19cf230.png)

![image](https://cloud.githubusercontent.com/assets/12042430/21413318/546565bc-c7c4-11e6-986b-ef80b7706bd0.png)

**Comment by jtf621** [comment]
Thanks @LASHirsh & @anap226.  I found the correct profile to edit and made the changes while I was at it.
