### ISSUE TITLE
School profile page: Move Parental Involvement to Community and Feedback under Community

### ISSUE THREAD

**Issue by basiacoulter** [codefordurham/school-navigator#398]
- Move "Parental Involvement" section from "Overview" tab to "Community and Feedback" tab under Community

**Comment by basiacoulter** [comment]
The columns of the headings on this page should read "Community" and "Feedback"

**Comment by schpatel** [comment]
So you want a header saying "Community" above Parent Involvement and a header saying "Feedback" above Testimonials? @basiacoulter

**Comment by basiacoulter** [comment]
This ticket has been merged and deployed.
