### ISSUE TITLE
Link overflows text area

### ISSUE THREAD

**Issue by b-r-broge** [codefordurham/school-navigator#428]
Found on https://durhamschoolnavigator.org/#/school/218/ under the 'School Offering' tab, a link is overflowing its container because it has no spaces to break on and interrupting the flow of the page.

![schoolnavigatorissue](https://user-images.githubusercontent.com/15382213/29590581-92338162-8768-11e7-8273-0d1651fddea1.png)

**Comment by alexlemann** [comment]
Closed in PR #431
