### ISSUE TITLE
Google Maps Requires API Key

### ISSUE THREAD

**Issue by KamiQuasi** [codefordurham/school-navigator#455]
Current site is getting errors due to the new-ish Google policy about API keys being required on every call.
https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

It means geocoding and other map api functions aren't working at all.

**Comment by KamiQuasi** [comment]
Fixed by commit 4dbbf10

**Comment by jtf621** [comment]
@KamiQuasi thanks.
