### ISSUE TITLE
Magnet/year-round schools aren't set on production

### ISSUE THREAD

**Issue by copelco** [codefordurham/school-navigator#54]
Magnet schools should match http://www.dpsnc.net/pages/Durham_Public_Schools/Our_Schools

**Comment by lemanal** [comment]
Some types are set to None

**Comment by jtf621** [comment]
@copelco @lemanal if you can get me access through the admin, I can check all the schools.  It looks like most are set from the website.  I will also check to see if charter is set since they have been added since this issue was raised.

**Comment by jtf621** [comment]
All are set to one of 
 Neighborhood
Magnet
Charter
Specialty
