### ISSUE TITLE
Automatic zooming makes it difficult to maintain situational awareness

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#81]
After entering the address. When I hover over the different assigned school, the map automatically zooms in or out to show the school zone.  This make it difficult keep track of where I am located on the map.

It would be easier to use if the map respected the level of zooming selected on the map so I can select my area of focus.

Or zoom out only, so the extent of the map stays constant.

**Comment by lemanal** [comment]
Is this ready to merge @victor-rocha ?

**Comment by victor-rocha** [comment]
it is as long as I get a +1
