### ISSUE TITLE
The list of school options exceeds the screen, scrolling to see the list moves the map

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#82]
When I view my option schools, the list of schools (13 schools) extends below the bottom of the screen.  Attempting to scroll the list first moves the the drop down by one or two lines without moving he map.  Further scrolling moves the entire map upwards and you loose awareness on the map.

It would be better if you could scroll the entire list without moving the map.  Or have theist collapse based on school type so you can see the entire list without moving the map.

**Comment by dsummersl** [comment]
https://github.com/codefordurham/school-navigator/pull/115
