### ISSUE TITLE
Pearsontown and Club Boulevard Elementary schools do not have a polygon

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#86]
search ``100 W Club Blvd`` and view options.

Pearsontown and Club Boulevard Elementary schools do not have a polygon

**Comment by copelco** [comment]
I researched this a bit tonight. Here's what I found:

* Club Boulevard has [a walk zone](http://www.dpsnc.net/files/_AaI1h_/183bf9414e39fd813745a49013852ec4/Program_Magnet_School_Lottery_FAQs_2015-16_English.pdf). There were two instances of Club Boulevard on the production DB. I've merged them and it looks correct now.
* Pearsontown has no [assigned attendance zone](http://www.dpsnc.net/files/_AaI16_/adf9dc39f01a638f3745a49013852ec4/Calendar_Magnet_Year-Round_School_Lottery_FAQS_English_2015-16_Assignments.pdf). It's a union of Bethesda, Creekside, Fayetteville Street, Forest View, Hope Valley, Lakewood, Parkwood, W.G. Pearson, E.K. Powe, Y.E. Smith, Southwest and C.C. Spaulding attendance zones.

**Comment by jtf621** [comment]
OK, this makes sense.
