### ISSUE TITLE
Split tab view to assigned, charter, magnet

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#94]
Can we add a 3rd tab to the assigned and options for all the charter schools and change options to magnet.  Right now options is really crowded and I think people will find less useful to have charters and magnets on the same tab.

**Comment by jtf621** [comment]
From my research on the zone issues, it appears that there are 3 categories a school falls under:
1. Assigned (might be better to call it automatic) this is the districted school for the address or if the address is in a walk zone.  Both cases are automatic assignment.  
2. Lottery preference, these are the schools with choice or priority given based on the address.  There are several different rules for the process
3. Open lottery (other magnet schools and charter schools) where your address does not give you any preference in the lottery process.

**Comment by NoOutlet** [comment]
Perhaps as an alternative solution to a 3rd tab, the key for the options list could act as a filter as well. Clicking the charter icon could toggle whether the charter schools are displayed or not.
This would require clear indication that the list is filtered though.

**Comment by sarahsba** [comment]
yeah, that could work if the filter function is clearly displayed.  we
could also use this to enable people to filter on other categories such as
year round, montissori, etc.

**Comment by lemanal** [comment]
One problem with this, @sarahsba, is that "Assigned" (or "Automatic" per @jtf621) may include Magnet schools even though they are not included on the Magnet tab.

For example, if I live Club Blvd School and I'm in the walk zone. Would I expect to see Club Blvd Magnet in the Magnet schools or the Assigned schools or both? Would it be indicated some how in the Assigned schools that it's a magnet?

Alex

**Comment by sarahsba** [comment]
The new layout looks good!

Could we avoid the issue, Alex, by changing "assigned" to "traditional" or
"regular" (regular is what they use on the NC Scorecards site)? Then,
separately, could we create a symbol or outlining for any magnet where
someone lives in the walk zone.

Do we have access to the walk zone data yet?

Alternatively, we could keep assigned, and just show a magnet school on the
assigned page and on the magnet page.  I think we'd still need some kind of
symbol, though, to indicate that it's a magnet on the assigned page.

Jeremy - to your earlier point about assigned/lottery preference/open
lottery, do we still need to come up with a separate way to indicate
lottery preference (ie is this different from being within a magnet's walk
zone?)  Is lottery preference location based?

**Comment by victor-rocha** [comment]
@jtf621 can we close this one? I forgot what else we need.

**Comment by sarahsba** [comment]
I think we still need to figure out a way to show when someone is in the
walk zone for a magnet school.

@jtf621 <https://github.com/jtf621> question for you: do we still need to
come up with a separate way to indicate lottery preference (ie is this
different from being within a magnet's walk zone?)  Is lottery preference
location based?

**Comment by jtf621** [comment]
@victor-rocha / @sarahsba 

I am closing the issue based on it's original definition and opening #135 to take on the comments added.

Feel free to reopen if you disagree
