### ISSUE TITLE
Content for pages

### ISSUE THREAD

**Issue by lemanal** [codefordurham/school-navigator#95]
* [ ] Navigating DPS [need more on Charters, proofreading]
* [ ] About

Contribute here: https://docs.google.com/document/d/1MpGr5PDVpOKHbsoDRJKI1sl9olm9Z_dZgeBIUUOaJKs/edit?usp=sharing

**Comment by lemanal** [comment]
@sarahsba are you working on this? Do we need a place to share copy drafts? Our plan is to make this copy hardcoded and not easy to edit in the admin interface.

**Comment by jtf621** [comment]
@adamajm here is the copy writing we need

**Comment by sarahsba** [comment]
not yet...would this be part of phase II?

**Comment by jtf621** [comment]
@sarahsba  / @adamajm  / @lemanal ,

I would suggest that we make a first draft of the “Navigating DPS” for the Phase 1 milestone.  We could get feedback on the usefulness and it will help us understand and communicate the non map based information a bit better.  

This would go toward the Goal: Remove friction for understanding the local school system (Improve drastically onexisting DPS web tools) 

Target group: Parents or Prospective Parents seeking to understand how their residential choice will impact where their kids can go to school.

What are your thoughts?

**Comment by lemanal** [comment]
@sarahsba ,This and #123 (the design of those pages) are marked for Phase I. Does that seem unreasonable? The text could be brief (mostly linking out to other resources) to start.

**Comment by adamajm** [comment]
Let's def get a v1 of text with minor effort put into design.

**Comment by adamajm** [comment]
Working google doc here: https://docs.google.com/document/d/1MpGr5PDVpOKHbsoDRJKI1sl9olm9Z_dZgeBIUUOaJKs/edit?usp=sharing

**Comment by adamajm** [comment]
for: Navigating DPS, need more on Charters, proofreading

**Comment by sarahsba** [comment]
ok, I'll work on this with Adam.

**Comment by jtf621** [comment]
Adam,

Looks like a very good first cut.  Thanks for taking this on.

Jeremy

**Comment by lemanal** [comment]
First draft is up, working, ready for feedback and iteration.
