### ISSUE TITLE
Sandy Ridge Is Fed By Multiple Schools

### ISSUE THREAD

**Issue by lemanal** [codefordurham/school-navigator#99]
Refs #73 

Search for Eno Valley in here: http://www.dpsnc.net/files/_AaI1h_/183bf9414e39fd813745a49013852ec4/Program_Magnet_School_Lottery_FAQs_2015-16_English.pdf

**Comment by jtf621** [comment]
It appears that Sandy Ridge should have priority choice zone and a priority zone.  The priority choice zone is on production via loading from the http://gisweb2.ci.durham.nc.us/arcgis/rest/services/DurhamMaps/DPS_Schools/MapServer api.

I cannot find the priority zone shape in the http://gisweb2.ci.durham.nc.us/arcgis/rest/services/DurhamMaps/DPS_Schools/MapServer api.

@lemanal, who at Durham County can we talk to determine if the API has the zone shape in it or if we have to hard code it based on the text in the referenced pdf?

**Comment by jtf621** [comment]
see #102, might be the same issue and solution.

**Comment by jtf621** [comment]
Based on http://dpsncapplication.com/Sandy_Ridge, the priority zone and transportation zone are the same (Mangum, Eno Valley, Little River, Easley, Holt, Hillandale and Glenn)

The htp://http://gisweb2.ci.durham.nc.us/arcgis/rest/services/DurhamMaps/DPS_ElementaryStudentAssignment/MapServer/6 has a zone for the "Sandy Ridge Transportation Services Area".  I plan on making the assumption that the "Sandy Ridge Transportation Services Area"  == "Sandy Ridge Priority Zone" and modify loadschools.py accordingly.
